# Generated by Django 5.2 on 2025-05-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
